import React, { createContext, useContext, useState } from 'react'

const LanguageContext = createContext(null)

const translations = {
  en: {
    // Navbar
    dashboard: 'Dashboard',
    categories: 'Categories',
    settings: 'Settings',
    signOut: 'Sign Out',
    upgradePro: 'Upgrade Pro',
    proPlan: 'PRO',

    // Dashboard
    subTitle: 'Overall Trading Performance & Advanced Analytics',
    totalTrades: 'Total Trades',
    winRate: 'Win rate',
    cumulativePnL: 'Cumulative P&L',
    profitFactor: 'Profit factor',
    expectancy: 'Expectancy / Trade',
    maxDrawdown: 'Max Drawdown',
    maxWinStreak: 'Max Win Streak',
    maxLossStreak: 'Max Loss Streak',
    avgWin: 'Average Win',
    avgLoss: 'Average Loss',
    equityCurve: 'Equity Curve',
    monthlyPnL: 'Monthly P&L',
    filterAll: 'All Time',
    filterMonth: 'This Month',
    filterWeek: 'This Week',
    filterToday: 'Today',
    noTradeData1: 'No trading data available — ',
    noTradeData2: 'Create a category and log your first trade',
    proFeatureTitle: '🔒 Pro Feature',
    proFeatureDesc: 'Upgrade to Pro to unlock advanced analytics, monthly P&L breakdowns, strategy performance, and more deep insights.',
    upgradeToPro: 'Upgrade to Pro',
    planVsNoPlan: 'Following Plan vs Not Following Plan',
    followingPlan: 'Following Plan',
    notFollowingPlan: 'Not Following Plan',
    winsLosses: 'Wins / Losses',
    bestTrade: '🏆 Best Trade',
    worstTrade: '💀 Worst Trade',
    catBySymbol: 'Categorized by Category',
    catByStrategy: 'Categorized by Strategy',
    catBySession: 'Categorized by Session',
    catByDirection: 'Categorized by Direction',
    perfByDay: 'Performance by Day of Week',
    mistakeAnalysis: 'Mistake Tags Analysis',
    recentTrades: 'Recent Trades',
    item: 'Item',
    trades: 'Trades',
    winRateTbl: 'Win Rate',
    profitLoss: 'Profit/Loss',
    totalLossImpact: 'Total Loss Impact',
    collapse: 'Collapse',
    showMore: 'Show {hidden} More Items (Total {total})',
    category: 'Category',
    strategy: 'Strategy',
    result: 'Result',
    date: 'Date',
    symbol: 'Symbol',
    direction: 'Direction',
    na: 'N/A',
    resultWin: '🟢 Win',
    resultLoss: '🔴 Loss',
    resultBE: '⚪ Breakeven',
    resultOpen: '🟦 Open',
    dayMon: 'Monday',
    dayTue: 'Tuesday',
    dayWed: 'Wednesday',
    dayThu: 'Thursday',
    dayFri: 'Friday',
    daySat: 'Saturday',
    daySun: 'Sunday',
    aiAnalyzePort: 'AI analyzes portfolio.',
    aiAnalyzeBtn: 'AI analyze',
    aiFree1: 'You are a professional trading coach reading a portfolio overview of a Free tier user.',
    aiFree2: 'Answer in English, concisely, using bullet points. Do not use a long intro.',
    aiFree3: 'Structure: 1) Short portfolio summary 2) Chart trend evaluation 3) 2-3 short advices',
    aiPro1: 'You are a professional trading coach reading an in-depth log from a Pro user.',
    aiPro2: 'Analyze the entire portfolio in detail. Answer in English, concisely, using bullet points.',
    aiStatAll: 'Overall Portfolio',
    aiStatCat: 'By Category/Symbol',
    aiStatStrat: 'By Strategy',
    aiStatSession: 'By Session',
    aiStatDir: 'By Direction (Buy/Sell)',
    equityTooltip: 'Total Equity',
    tradeNumberLabel: 'Trade #',

    // Category
    Categories: 'Categories',
    categorySub: 'Organize your trades by symbols you create yourself',
    categoryLimitReached: 'Category Limit Reached',
    categoryLimitDesc: 'You have reached the maximum of {limit} categories on the {plan} plan. You can still view past trades, but you cannot record new ones.',
    addCategory: '+ Add Category',
    exampleCategory: 'Category name, e.g., EURUSD, Gold, BTCUSD',
    noCategories: 'No categories yet — add your first category above',
    delete: 'Delete',
    categoryLocked: '🔒 Locked Categories (Upgrade to Pro to unlock)',

    // CategoryTrades
    allCat: '← All Categories',
    newTrade: '+ Record New Trade',
    lockedCategory: '🔒 Locked Category (Upgrade to Pro to unlock)',
    lockedCategoryDesc: 'This category is locked because you have exceeded the {limit} category limit of the {plan} plan. You can still view past trades, but you cannot record new ones.',
    upgradeToProUnlock: 'Upgrade to Pro to Unlock',
    totalPnL: 'Total P&L',
    aiAnalyze: 'AI analyzes {category}',
    aiDisabledHint: 'AI analysis is disabled for locked categories. Upgrade to Pro to unlock.',
    noTradesInCategory: 'No trades recorded in this category — start recording your first trade',

    // TradeForm
    Before: 'Before Trade',
    After: 'After Trade',
    tradeFormTitle: 'Record Trade',
    imageLocked: 'Image Locked',
    imageLockedDesc: 'This image is locked. Upgrade to Pro to view your extra charts.',
    clickToEnlarge: 'Click to enlarge',
    categoryLockedDesc: 'This category is locked. Upgrade to Pro to add new trades.',
    imageUploadFailed: 'Image upload failed',
    monthlyLimitDesc: 'Your',
    monthlyLimitDesc2: 'plan is limited to',
    monthlyLimitDesc3: 'trades per month.',
    deleteTradeConfirm: 'Delete this trade?',
    proOnly: 'Pro Only',
    removeImage: '✕ Remove',
    uploadingCompressing: 'Uploading & Compressing...',
    tradeLocked: '🔒 Trade Locked',
    tradeLockedDesc: 'This trade belongs to a locked category. Editing and AI analysis are disabled. You can only view or delete this trade.',
    monthlyTradeLimitReached: 'Monthly Trade Limit Reached',
    monthlyTradeLimitReachedDesc: 'You have reached the maximum of {maxLimit} trades for this month on the {planName} plan.',
    AIAnalyzetrade: 'AI analyzes this trade.',
    monthlyTradesUsed: 'Monthly Trades Used:',
    dateAndTimeOfTrade: 'Date & time of trade',
    BeforeTrading: 'Before Trading',
    Entry: 'Entry',
    StopLoss: 'Stop Loss',
    TakeProfit: 'Take Profit',
    LotSize: 'Lot Size',
    Timeframe: 'Timeframe',
    session: 'Session',
    Strategy: 'Strategy',
    Setup: 'Setup',
    TradingPlan: 'Trading Plan',
    News: 'News',
    ChartBeforeTrading: 'Chart Before Trading',
    AfterTrading: 'After Trading',
    Exit: 'Exit',
    ProfitLoss: 'Profit/Loss',
    Result: 'Result',
    Duration: 'Duration (Min)',
    ReasonForWinning: 'Reason for Winning',
    ReasonForLosing: 'Reason for Losing',
    LessonLearned: 'Lesson Learned',
    FollowedTradingPlan: 'Followed Trading Plan',
    MistakeTags: 'Mistake Tags',
    ChartAfterTrading: 'Chart After Trading',
    Saving: 'Saving...',
    SaveTrade: 'Save Trade',
    deleteTrade: 'Delete Trade',
    EditTrade: 'Edit Trade',
    RecordNewTrade: 'Record New Trade',

    // AIInsight
    quota: 'Quota',
    viewAnalysis: '▼ View Analysis',
    hideAnalysis: '▲ Hide Analysis',
    regenerate: 'Regenerate',
    Analyzing: 'Analyzing...',
    quotaEmpty: 'You have reached your daily AI limit ({remaining}/{max}). {upgradeMessage}',
    upgradeMessageFree: 'Upgrade to Pro for more daily analyses.',
    upgradeMessagePro: 'Please try again tomorrow.',
    canProceed: 'Failed to update AI usage quota. Please try again.',
    analysisError: 'An error occurred during analysis.',
    Analyzedon: 'Analyzed on',
    geminiApiKeyMissing: 'AI not found. Please visit the Settings page to contact the administrator.',
    dataStale: 'Data has changed since last analysis. Click "Regenerate" to update.',
    showInsights: 'Click the button above to generate insights.',

    // Settings
    settingsDesc: 'Manage your account preferences and security.',
    changePassword: 'Change Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    passwordMismatch: 'Passwords do not match.',
    passwordTooShort: 'Password must be at least 6 characters.',
    passwordUpdated: 'Password has been updated successfully.',
    updating: 'Updating...',
    updatePasswordBtn: 'Update Password',
    contactAdminLine: 'Contact Admin (Line)',

    // 🌟 Upgrade Page
    backToDashboard: '← Back to Dashboard',
    upgradeTitle: 'Upgrade Your Plan',
    upgradeSub: 'Choose the right plan to accelerate your trading journey.',
    perMonth: '/ month',
    currentPlanBtn: 'Current Plan',
    recommendedBadge: 'RECOMMENDED',
    activeBtn: 'Active',
    connectingBtn: 'Connecting...',
    upgradeToProBtn: 'Upgrade to Pro',
    comingSoonBtn: 'Coming Soon...',
    paymentError: 'Payment Error:',
    
    // Free Plan
    freePlanName: 'Starter (Free)',
    freeF1: '✓ Record up to 15 trades / month',
    freeF2: '✓ Create up to 2 categories',
    freeF3: '✓ Basic AI trade summaries (1 time / day)',
    freeF4: '✓ Basic statistical overview',
    freeF5: '✓ Attach 2 images / trade',

    // Pro Plan
    proPlanName: 'Pro Plan',
    proF1: '✓ Record up to 120 trades / month',
    proF2: '✓ Create up to 10 categories',
    proF3: '✓ Advanced AI analysis (5 times / day)',
    proF4: '✓ Unlock all advanced stats',
    proF5: '✓ Expanded storage to 4 images / trade',

    // Premium Plan
    premPlanName: 'Pro Premium',
    premF1: '✓ Record up to 500 trades / month',
    premF2: '✓ Unlimited categories',
    premF3: '✓ Deep AI analysis (20 times / day)',
    premF4: '✓ Unlock all advanced stats',
    premF5: '✓ AI Vision (Reads charts from images)',
    premF6: '✓ Expanded storage to 8 images / trade',

    // 🌟 แจ้งเตือนการพัฒนา
    devAlertTitle: '🚧 Under Development',
    devAlertDesc: 'This application is currently in the development phase. Some features may be incomplete or subject to change. Thank you for testing!',
    devAlertBtn: 'I Understand',
  },
  th: {
    // Navbar
    dashboard: 'แดชบอร์ด',
    categories: 'หมวดหมู่',
    settings: 'ตั้งค่า',
    signOut: 'ออกระบบ',
    upgradePro: 'อัปเกรด Pro',
    proPlan: 'PRO',

    // Dashboard
    subTitle: 'ภาพรวมผลการเทรดและสถิติเชิงลึก',
    totalTrades: 'จำนวนเทรดทั้งหมด',
    winRate: 'อัตราการชนะ',
    cumulativePnL: 'กำไร/ขาดทุนสะสม',
    profitFactor: 'สัดส่วนกำไร',
    expectancy: 'ค่าคาดหวังเฉลี่ย / ไม้',
    maxDrawdown: 'ขาดทุนสะสมสูงสุด',
    maxWinStreak: 'ชนะติดต่อกันสูงสุด',
    maxLossStreak: 'แพ้ติดต่อกันสูงสุด',
    avgWin: 'กำไรเฉลี่ย (ไม้ชนะ)',
    avgLoss: 'ขาดทุนเฉลี่ย (ไม้แพ้)',
    equityCurve: 'กราฟการเติบโตของพอร์ต',
    monthlyPnL: 'กำไร/ขาดทุนรายเดือน',
    filterAll: 'ทั้งหมด',
    filterMonth: 'เดือนนี้',
    filterWeek: 'สัปดาห์นี้',
    filterToday: 'วันนี้',
    noTradeData1: 'ยังไม่มีข้อมูลการเทรด — ',
    noTradeData2: 'สร้างหมวดหมู่และเริ่มบันทึกไม้แรกของคุณ',
    proFeatureTitle: '🔒 ฟีเจอร์ระดับ Pro',
    proFeatureDesc: 'อัปเกรดเป็น Pro เพื่อปลดล็อกสถิติเชิงลึก กราฟสรุปกำไรรายเดือน สถิติตามกลยุทธ์ และบทวิเคราะห์ทั้งหมด',
    upgradeToPro: 'อัปเกรดเป็น Pro',
    planVsNoPlan: 'ทำตามแผน vs นอกแผน',
    followingPlan: 'ทำตามแผน',
    notFollowingPlan: 'นอกแผน',
    winsLosses: 'ชนะ / แพ้',
    bestTrade: '🏆 ไม้ที่กำไรสูงสุด',
    worstTrade: '💀 ไม้ที่ขาดทุนสูงสุด',
    catBySymbol: 'แยกตามหมวดหมู่ (Category)',
    catByStrategy: 'แยกตามกลยุทธ์ (Strategy)',
    catBySession: 'แยกตามช่วงเวลา (Session)',
    catByDirection: 'แยกตามทิศทาง (Buy/Sell)',
    perfByDay: 'ประสิทธิภาพรายวัน (Day of Week)',
    mistakeAnalysis: 'วิเคราะห์ข้อผิดพลาด (Mistake Tags)',
    recentTrades: 'ประวัติการเทรดล่าสุด',
    item: 'รายการ',
    trades: 'ไม้',
    winRateTbl: 'อัตราชนะ',
    profitLoss: 'กำไร/ขาดทุน',
    totalLossImpact: 'ผลกระทบยอดขาดทุน',
    collapse: 'ย่อเก็บ',
    showMore: 'แสดงเพิ่มอีก {hidden} รายการ (รวม {total})',
    category: 'หมวดหมู่',
    strategy: 'กลยุทธ์',
    result: 'ผลลัพธ์',
    date: 'วันที่',
    symbol: 'สัญลักษณ์',
    direction: 'ทิศทาง',
    na: 'ไม่มีข้อมูล',
    resultWin: '🟢 ชนะ',
    resultLoss: '🔴 แพ้',
    resultBE: '⚪ เสมอตัว',
    resultOpen: '🟦 เปิดอยู่',
    dayMon: 'จันทร์',
    dayTue: 'อังคาร',
    dayWed: 'พุธ',
    dayThu: 'พฤหัสบดี',
    dayFri: 'ศุกร์',
    daySat: 'เสาร์',
    daySun: 'อาทิตย์',
    aiAnalyzePort: 'AI วิเคราะห์พอร์ตการลงทุน',
    aiAnalyzeBtn: 'วิเคราะห์ด้วย AI',
    aiFree1: 'คุณเป็นโค้ชเทรดมืออาชีพ กำลังอ่านสถิติภาพรวมพอร์ตของผู้ใช้แพ็กเกจ Free',
    aiFree2: 'ตอบเป็นภาษาไทย กระชับ ตรงประเด็น ใช้หัวข้อย่อยเป็นหลัก ไม่ต้องมีคำนำยืดยาว',
    aiFree3: 'โครงสร้างคำตอบ: 1) สรุปภาพรวมพอร์ตสั้นๆ 2) ประเมินทิศทางกราฟ 3) คำแนะนำสั้นๆ 2-3 ข้อ',
    aiPro1: 'คุณเป็นโค้ชเทรดมืออาชีพที่กำลังอ่านสถิติเชิงลึกจากสมุดบันทึกการเทรดของผู้ใช้แพ็กเกจ Pro',
    aiPro2: 'ช่วยวิเคราะห์พอร์ตทั้งหมดของเขาอย่างละเอียด ตอบเป็นภาษาไทย กระชับ ตรงประเด็น ใช้หัวข้อย่อย (bullet)',
    aiStatAll: 'ภาพรวมพอร์ตทั้งหมด',
    aiStatCat: 'แยกตามหมวด/สัญลักษณ์',
    aiStatStrat: 'แยกตาม Strategy',
    aiStatSession: 'แยกตาม Session',
    aiStatDir: 'แยกตามทิศทาง (Buy/Sell)',
    equityTooltip: 'ยอดเงินรวม',
    tradeNumberLabel: 'ไม้ที่ ',

    // Category
    Categories: 'หมวดหมู่',
    categorySub: 'จัดระเบียบการเทรดของคุณตามสัญลักษณ์ที่คุณสร้างเอง',
    categoryLimitReached: 'จำนวนหมวดหมู่ครบแล้ว',
    categoryLimitDesc: 'คุณได้ใช้หมวดหมู่ครบ {limit} รายการในแพ็กเกจ {plan} แล้ว คุณยังสามารถดูการเทรดที่ผ่านมาได้ แต่ไม่สามารถบันทึกการเทรดใหม่ได้',
    addCategory: '+ เพิ่มหมวดหมู่',
    exampleCategory: 'ชื่อหมวดหมู่ เช่น EURUSD, Gold, BTCUSD',
    noCategories: 'ยังไม่มีหมวดหมู่ — เพิ่มหมวดหมู่แรกของคุณด้านบน',
    delete: 'ลบ',
    categoryLocked: '🔒 หมวดหมู่ถูกล็อก (อัปเกรดเป็น Pro เพื่อปลดล็อก)',

    // CategoryTrades
    allCat: '← หมวดหมู่ทั้งหมด',
    newTrade: '+ บันทึกการเทรดใหม่',
    lockedCategory: '🔒 หมวดหมู่ถูกล็อก (อัปเกรดเป็น Pro เพื่อปลดล็อก)',
    lockedCategoryDesc: 'หมวดหมู่นี้ถูกล็อกเพราะคุณได้ใช้หมวดหมู่เกิน {limit} รายการในแพ็กเกจ {plan} คุณยังสามารถดูการเทรดที่ผ่านมาได้ แต่ไม่สามารถบันทึกการเทรดใหม่ได้',
    upgradeToProUnlock: 'อัปเกรดเป็น Pro เพื่อปลดล็อก',
    totalPnL: 'กำไร/ขาดทุนรวม',
    aiAnalyze: 'AI วิเคราะห์ {category}',
    aiDisabledHint: 'การวิเคราะห์ด้วย AI ถูกปิดใช้งานสำหรับหมวดหมู่ที่ถูกล็อก อัปเกรดเป็น Pro เพื่อปลดล็อก',
    noTradesInCategory: 'ยังไม่มีการบันทึกการเทรดในหมวดหมู่นี้ — เริ่มบันทึกการเทรดแรกของคุณ',

    // TradeForm
    Before: 'ก่อนเข้าเทรด',
    After: 'หลังออกเทรด',
    tradeFormTitle: 'บันทึกการเทรด',
    imageLocked: 'รูปภาพถูกล็อก',
    imageLockedDesc: 'รูปภาพนี้ถูกล็อก อัปเกรดเป็น Pro เพื่อดูกราฟเพิ่มเติมของคุณ',
    clickToEnlarge: 'คลิกเพื่อขยาย',
    categoryLockedDesc: 'หมวดหมู่นี้ถูกล็อก อัปเกรดเป็น Pro เพื่อบันทึกการเทรดใหม่',
    imageUploadFailed: 'อัปโหลดรูปภาพล้มเหลว',
    monthlyLimitDesc: 'แพ็กเกจ',
    monthlyLimitDesc2: 'ของคุณจำกัดการบันทึกการเทรดไว้ที่',
    monthlyLimitDesc3: 'ไม้ต่อเดือน',
    deleteTradeConfirm: 'คุณต้องการลบการเทรดนี้หรือไม่?',
    proOnly: 'เฉพาะ Pro เท่านั้น',
    removeImage: '✕ ลบ',
    uploadingCompressing: 'กำลังอัปโหลดและบีบอัด...',
    tradeLocked: '🔒 ไม้นี้ถูกล็อก',
    tradeLockedDesc: 'ไม้นี้อยู่ในหมวดหมู่ที่ถูกล็อก การแก้ไขและการวิเคราะห์ด้วย AI ถูกปิดใช้งาน คุณสามารถดูหรือ ลบ ไม้นี้ได้เท่านั้น',
    monthlyTradeLimitReached: 'จำนวนการเทรดต่อเดือนครบแล้ว',
    monthlyTradeLimitReachedDesc: 'คุณได้บันทึกการเทรดครบ {maxLimit} ไม้สำหรับเดือนนี้ในแพ็กเกจ {planName} แล้ว',
    AIAnalyzetrade: 'AI วิเคราะห์ไม้นี้',
    monthlyTradesUsed: 'จำนวนการเทรดต่อเดือนที่ใช้แล้ว:',
    dateAndTimeOfTrade: 'วันที่และเวลาของการเทรด',
    BeforeTrading: 'ก่อนเข้าเทรด',
    Entry: 'ราคาเข้า (Entry)',
    StopLoss: 'จุดตัดขาดทุน (SL)',
    TakeProfit: 'จุดทำกำไร (TP)',
    LotSize: 'ขนาดหลอด (Lot Size)',
    Timeframe: 'กรอบเวลา (Timeframe)',
    session: 'ช่วงเวลาตลาด (Session)',
    Strategy: 'กลยุทธ์ (Strategy)',
    Setup: 'รูปแบบการเข้าเทรด',
    TradingPlan: 'แผนการเทรด',
    News: 'ข่าวสาร',
    ChartBeforeTrading: 'กราฟก่อนเข้าเทรด',
    AfterTrading: 'หลังออกเทรด',
    Exit: 'ราคาออก (Exit)',
    ProfitLoss: 'กำไร/ขาดทุน',
    Result: 'ผลลัพธ์',
    Duration: 'ระยะเวลา (นาที)',
    ReasonForWinning: 'เหตุผลที่ชนะ',
    ReasonForLosing: 'เหตุผลที่แพ้',
    LessonLearned: 'บทเรียนที่ได้เรียนรู้',
    FollowedTradingPlan: 'ทำตามแผนการเทรด',
    MistakeTags: 'แท็กข้อผิดพลาด',
    ChartAfterTrading: 'กราฟหลังออกเทรด',
    Saving: 'กำลังบันทึก...',
    SaveTrade: 'บันทึกการเทรด',
    deleteTrade: 'ลบการเทรด',
    EditTrade: 'แก้ไขการเทรด',
    RecordNewTrade: 'บันทึกการเทรดใหม่',

    // AIInsight
    quota: 'คงเหลือ',
    viewAnalysis: '▼ ดูบทวิเคราะห์',
    hideAnalysis: '▲ ซ่อนบทวิเคราะห์',
    regenerate: 'วิเคราะห์ใหม่',
    Analyzing: 'กำลังวิเคราะห์...',
    quotaEmpty: 'คุณใช้โควต้าวันนี้ครบแล้ว ({remaining}/{max}) {upgradeMessage}',
    upgradeMessageFree: 'อัปเกรดเป็น Pro เพื่อวิเคราะห์ได้มากขึ้น',
    upgradeMessagePro: 'กรุณาลองใหม่ในวันพรุ่งนี้',
    canProceed: 'ไม่สามารถอัปเดตโควต้าการใช้งาน AI ได้ กรุณาลองใหม่อีกครั้ง',
    analysisError: 'เกิดข้อผิดพลาดระหว่างการวิเคราะห์',
    Analyzedon: 'วิเคราะห์เมื่อ',
    geminiApiKeyMissing: 'ไม่พบ AI กรุณาไปที่หน้าตั้งค่าเพื่อแจ้งผู้ดูแลระบบ',
    dataStale: 'ข้อมูลมีการเปลี่ยนแปลงตั้งแต่การวิเคราะห์ล่าสุด คลิก "วิเคราะห์ใหม่" เพื่ออัปเดต',
    showInsights: 'คลิกปุ่มด้านบนเพื่อสร้างข้อมูลเชิงลึก',

    // Settings
    settingsDesc: 'จัดการการตั้งค่าบัญชีและความปลอดภัยของคุณ',
    changePassword: 'เปลี่ยนรหัสผ่าน',
    newPassword: 'รหัสผ่านใหม่',
    confirmNewPassword: 'ยืนยันรหัสผ่านใหม่',
    passwordMismatch: 'รหัสผ่านไม่ตรงกัน',
    passwordTooShort: 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
    passwordUpdated: 'อัปเดตรหัสผ่านสำเร็จ',
    updating: 'กำลังอัปเดต...',
    updatePasswordBtn: 'อัปเดตรหัสผ่าน',
    contactAdminLine: 'ติดต่อแอดมิน (Line)',

    // 🌟 Upgrade Page
    backToDashboard: '← กลับสู่แดชบอร์ด',
    upgradeTitle: 'อัปเกรดแพ็กเกจของคุณ',
    upgradeSub: 'เลือกแพ็กเกจที่ใช่เพื่อเร่งความสำเร็จในการเทรดของคุณ',
    perMonth: '/ เดือน',
    currentPlanBtn: 'แพ็กเกจปัจจุบัน',
    recommendedBadge: 'แนะนำ',
    activeBtn: 'ใช้งานอยู่',
    connectingBtn: 'กำลังเชื่อมต่อ...',
    upgradeToProBtn: 'อัปเกรดเป็น Pro',
    comingSoonBtn: 'เร็วๆ นี้...',
    paymentError: 'ข้อผิดพลาดการชำระเงิน:',
    
    // Free Plan
    freePlanName: 'เริ่มต้น (ฟรี)',
    freeF1: '✓ บันทึกการเทรดสูงสุด 15 ไม้ / เดือน',
    freeF2: '✓ สร้างหมวดหมู่สูงสุด 2 รายการ',
    freeF3: '✓ สรุปการเทรดด้วย AI พื้นฐาน (1 ครั้ง / วัน)',
    freeF4: '✓ สถิติภาพรวมพื้นฐาน',
    freeF5: '✓ แนบรูปภาพ 2 รูป / ไม้',

    // Pro Plan
    proPlanName: 'แพ็กเกจ Pro',
    proF1: '✓ บันทึกการเทรดสูงสุด 120 ไม้ / เดือน',
    proF2: '✓ สร้างหมวดหมู่สูงสุด 10 รายการ',
    proF3: '✓ วิเคราะห์เชิงลึกด้วย AI (5 ครั้ง / วัน)',
    proF4: '✓ ปลดล็อกสถิติเชิงลึกทั้งหมด',
    proF5: '✓ ขยายพื้นที่แนบรูปภาพ 4 รูป / ไม้',

    // Premium Plan
    premPlanName: 'แพ็กเกจ Pro Premium',
    premF1: '✓ บันทึกการเทรดสูงสุด 500 ไม้ / เดือน',
    premF2: '✓ สร้างหมวดหมู่ไม่จำกัด',
    premF3: '✓ วิเคราะห์ขั้นสูงสุดด้วย AI (20 ครั้ง / วัน)',
    premF4: '✓ ปลดล็อกสถิติเชิงลึกทั้งหมด',
    premF5: '✓ AI Vision (อ่านกราฟจากรูปภาพ)',
    premF6: '✓ ขยายพื้นที่แนบรูปภาพ 8 รูป / ไม้',

    // 🌟 แจ้งเตือนการพัฒนา
    devAlertTitle: '🚧 เว็บไซต์อยู่ในช่วงพัฒนา',
    devAlertDesc: 'ระบบนี้กำลังอยู่ในช่วงการพัฒนาและทดสอบ ฟีเจอร์บางส่วนอาจยังไม่สมบูรณ์หรืออาจมีการเปลี่ยนแปลง ขออภัยในความไม่สะดวกครับ!',
    devAlertBtn: 'รับทราบ',
  }
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en')

  const toggleLang = () => {
    setLang((prev) => (prev === 'en' ? 'th' : 'en'))
  }

  // 🌟 เพิ่มระบบ String Interpolation เปลี่ยนตัวแปรในวงเล็บปีกกา
  const t = (key, params = {}) => {
    let text = translations[lang][key] || key
    if (Object.keys(params).length > 0 && typeof text === 'string') {
      Object.keys(params).forEach((paramKey) => {
        text = text.replace(new RegExp(`{${paramKey}}`, 'g'), params[paramKey])
      })
    }
    return text
  }

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}